### ISSUE TITLE
Error running db_build.py 

### ISSUE THREAD

**Issue by mikel-brostrom** [MapariAbdullah/Llama2-Custom-document-QA#1]
Just cloned and try to run `db_build.py` . I get the following:

```bash
(env) mikel@T4-3:/T4-drives/llm/mikel/Llama2-Custom-document-QA$ python db_build.py 
Traceback (most recent call last):
  File "/T4-drives/llm/mikel/Llama2-Custom-document-QA/db_build.py", line 34, in <module>
    run_db_build()
  File "/T4-drives/llm/mikel/Llama2-Custom-document-QA/db_build.py", line 22, in run_db_build
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=cfg.CHUNK_SIZE,
  File "/T4-drives/llm/mikel/Llama2-Custom-document-QA/env/lib/python3.10/site-packages/langchain/text_splitter.py", line 596, in __init__
    super().__init__(keep_separator=keep_separator, **kwargs)
  File "/T4-drives/llm/mikel/Llama2-Custom-document-QA/env/lib/python3.10/site-packages/langchain/text_splitter.py", line 76, in __init__
    if chunk_overlap > chunk_size:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by MapariAbdullah** [comment]
In your config.yml file make sure that both CHUNK_SIZE and CHUNK_OVERLAP are numbers and not strings

Or you can manually replace this in your db_build.py file: 
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500,
                                                   chunk_overlap=50)

**Comment by mikel-brostrom** [comment]
Thx. THis worked:

```
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500,
chunk_overlap=50) 
```
